# Generated by Django 5.0.4 on 2024-04-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_video_delete_kurslar_delete_mentorlar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
